modLoader="javafml"
loaderVersion="[35,)"
license="See GitHub repository for details"

[[mods]]
modId="prayers"
version="${version}"
displayName="Prayers"
authors="superckl"
description="Adds (nostalgic) prayers to Minecraft."

[[dependencies.biometweaker]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version}"
    ordering="NONE"
    side="BOTH"

[[dependencies.biometweaker]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version}"
    ordering="NONE"
    side="BOTH"
